spring:
  application:
    name: customerIdentityDemo
  datasource:
    url: jdbc:postgresql://localhost:5432/customer_identity_db
    username: demo_user
    password: demo_pass
    driver-class-name: org.postgresql.Driver
management:
  endpoints:
    web:
      exposure:
        include: "*"

order-service:
  url: http://localhost:8081