spring:
  application:
    name: customerIdentityDemo
  datasource:
    url: jdbc:postgresql://localhost:5432/customer_identity_db
    username: demo_user
    password: demo_pass
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    locations: classpath:db/migration
  profiles:
    active: dev

order-service:
  url: http://localhost:8081

management:
  endpoints:
    web:
      exposure:
        include: "*"

# JWT Configuration
jwt:
  secret: myVerySecretJwtKeyThatShouldBeAtLeast256BitsLongForProperSecurityAndShouldBeStoredInEnvironmentVariables
  expiration: 3600